### ISSUE TITLE
Annoying popup during registration error

### ISSUE THREAD

**Issue by iqbalbaharum** [iqbalbaharum/fekreno#2]
**Describe the bug**
Registration Error modal will keep popup without click Register

**To Reproduce**
1. Go to Sign Up page
2. Click on Submit button
3. Try typing anything at any box
4. Modal will keep popup on keypress

**Expected behavior**
Registration Popup should only appear after **Register button** is click and there's error in request.

**Comment by Arexxa** [comment]
| Scenario | Expected result |
| User fill up all the fields and click submit | success dialog popup, user created |
| User didn't fill up the username and click submit | error dialog popup, user not created |
| User didn't fill up the username and click submit, error popup , refill the fields and click submit | error popup at first time then close. Then, success dialog popup, user created |
| User didn't fill up username and click submit, close the dialog then click submit | error message popup first time, then popup again, user not created |
| User didn't fill up username and click submit, Close popup, refill username and submit | error message popup for the first time, success message popup, User created |
