### ISSUE TITLE
[ BUG ] Tabs in Application page doesn't change after click Fill In Form button

### ISSUE THREAD

**Issue by zh6ziq** [iqbalbaharum/fekreno#24]
**Describe the bug**
When I clicked the **Fill In Form** button to apply, nothing happened to the current page. I need to refresh the browser to see the changes.

**To Reproduce**
1. As a User, go to **Application** page.
2. Click on one of the projects listed to apply.
3. Click on **Fill In Form** button. Reference: _Screenshot 1_.
4. After the button is clicked, there is no actions afterwards.

**Expected behavior**
After click **Fill In Form** button, the tabs in **Application** will change. Reference: _Screenshot 2_.

**Screenshots**
##### Screenshot 1
Current Behavior
![Screenshot 2021-01-30 215334](https://user-images.githubusercontent.com/71532216/106358767-2b96d600-6349-11eb-909f-f66e0ebfd46c.png)

##### Screenshot 2
Expected Behavior
![Screenshot 2021-01-30 215454](https://user-images.githubusercontent.com/71532216/106358973-4d448d00-634a-11eb-9285-791bdd4b57fa.png)

**Desktop:**
 - OS: [Windows]
 - Browser [chrome]
 - Version [ 88.0.4324.104 (Official Build) (64-bit)]

**Comment by iqbalbaharum** [comment]
![image](https://user-images.githubusercontent.com/22128538/106445575-24dba080-64ba-11eb-9aef-3fe475f50517.png)

As i clicked the Fill In Form. It changes the tabs automatically.

Could you share that particular Application JSON, maybe I there's issue in the application.

**Comment by zh6ziq** [comment]
https://user-images.githubusercontent.com/71532216/106466800-c4a72780-64d6-11eb-8044-33dd66d0101e.mp4

Here is a short video regarding the bug that I've encountered.

When I check the `http request` in network, it return error `status code: 500` as below:

```js
{error: {statusCode: 500, message: "Internal Server Error"}}
    error: {statusCode: 500, message: "Internal Server Error"}
       message: "Internal Server Error"
         statusCode: 500
```

I can only see the changes after refresh the browser or change to another page and come back to 'Application' page.

The process for this page can be found in file `pages/User/Application.vue`

**Comment by iqbalbaharum** [comment]
Noted. the Issue come from the SMTP. Closing this issue.
