### ISSUE TITLE
The tagging for repository is duplicating at Project page repository tab

### ISSUE THREAD

**Issue by HaziqRauf** [iqbalbaharum/fekreno#31]
**Describe the bug**
The tagging for repository is duplicated for each time I clicked the repository link at repository tab.

**To Reproduce**
1. Go to 'Project' page.
2. Click on one of the 'listed project'.
3. Click at the 'Repositories' tab.
4. Click on one of the 'listed repositories'.
5. After one of the listed repository is clicked. The repository comment section and tags will be shown. Reference: _Screenshot 1_
6. Repeat the step 1 until step 4. The repository tag will duplicate the original count of the repository tag, Reference: _Screenshot 2_

**Expected behavior**
The repository tag will show the exact quantity of the tags based on the repository constantly and will not change even though how many time the repository link was clicked. Reference: _Screenshot 1_

**Screenshots**

**Screenshot 1**
![image](https://user-images.githubusercontent.com/68379644/106487144-56ba2a80-64ed-11eb-8149-6bea988d929a.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/68379644/106487954-29ba4780-64ee-11eb-9371-536e98e29366.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [18363.1316]

**Comment by iqbalbaharum** [comment]
Connected with Repository Note as well
