### ISSUE TITLE
Able to see other user profile

### ISSUE THREAD

**Issue by iqbalbaharum** [iqbalbaharum/fekreno#76]
**Is your feature request related to a problem? Please describe.**
As a user, I can see other people profile.

**Describe the solution you'd like**

1. Go to `/iqbalbaharum`
2. Display user detail with similar My Account design.
 
**Additional context**
Endpoints:
`GET /users/name/{username}/profile`

**Comment by iqbalbaharum** [comment]
Test case:

1. Condition: Authenticated user, Go to '/' redirect to own user profile
2. Condition: Authenticated user, Go to '/<username>' redirect to other user profile
3. Condition: Not authenticated user, Go to'/' redirect to website
4. Condition: Not authenticated user, Go to '/<username' redirect to other user profile

**Comment by zh6ziq** [comment]
Hi @iqbalbaharum . I need clarification for this issue. Is it for search users by their username? Do I need to create a `search bar` and then, the results from the search list can redirect us to their profile?
